# Generated by Django 3.0.5 on 2023-06-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_teacherextra_class_incharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra',
            name='salary',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
