# Generated by Django 3.0.5 on 2023-06-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20230610_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='roll',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
