# Generated by Django 3.0.5 on 2023-06-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_feerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feerecord',
            name='status',
        ),
        migrations.AddField(
            model_name='feerecord',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
