# Generated by Django 3.0.5 on 2023-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20230611_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feerecord',
            name='paid',
        ),
        migrations.AddField(
            model_name='feerecord',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=7),
        ),
    ]
