# Generated by Django 3.0.5 on 2023-06-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20230611_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
