# Generated by Django 3.0.5 on 2023-06-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_feerecord_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feerecord',
            unique_together={('student', 'month')},
        ),
    ]
