# Generated by Django 3.0.5 on 2023-06-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20230611_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterUniqueTogether(
            name='feerecord',
            unique_together={('student', 'month', 'year')},
        ),
    ]
