# Generated by Django 3.0.5 on 2023-06-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20230611_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='cnic',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='father_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
