# Generated by Django 3.0.5 on 2023-06-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20230613_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentextra',
            old_name='father_name',
            new_name='fathername',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='status',
        ),
    ]
