# Generated by Django 3.0.5 on 2023-06-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20230613_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='fathername',
        ),
    ]
