# Generated by Django 3.0.5 on 2023-06-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_remove_studentextra_fathername'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='father',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='fcnic',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
