# Generated by Django 3.0.5 on 2023-06-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20230613_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
