# Generated by Django 3.0.5 on 2023-06-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_studentextra_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='cnic',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='father',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
