# Generated by Django 3.0.5 on 2023-06-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_auto_20230613_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
